#ifndef azhgh22_parser_includes
#define azhgh22_parser_includes

#include "../commands/add.h"
#include "../commands/addi.h"
#include "../commands/beq.h"
#include "../commands/bge.h"
#include "../commands/bgt.h"
#include "../commands/ble.h"
#include "../commands/blt.h"
#include "../commands/bne.h"
#include "../commands/call.h"
#include "../commands/div.h"
#include "../commands/j.h"
#include "../commands/jal.h"
#include "../commands/jalr.h"
#include "../commands/jr.h"
#include "../commands/lb.h"
#include "../commands/lh.h"
#include "../commands/li.h"
#include "../commands/lw.h"
#include "../commands/mul.h"
#include "../commands/mv.h"
#include "../commands/ret.h"
#include "../commands/sb.h"
#include "../commands/sh.h"
#include "../commands/sub.h"
#include "../commands/sw.h"

#endif